name: "Security Scan"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  analyze:
    name: Analyze Code
    runs-on: ubuntu-latest
    permissions:
      security-events: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # This runs CodeQL to find vulnerabilities in your code
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: 'javascript' # Even if it's just HTML, this covers JS injections

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3

    # This runs Checkov to scan your YAML files (like your deployment.yaml)
    - name: Run Checkov
      uses: bridgecrewio/checkov-action@master
      with:
        directory: .
        framework: cloudformation,kubernetes,terraform,dockerfile,github_actions
